 echo "Start linting"
 linterResult=$(npm run lint);
 echo "Start audit"
 auditResult=$(npm run check-deps);
 echo "Start testing"
 npm run test;
 npm run sonarqube
 echo "linter: $linterResult";
 echo "audit: $auditResult";